### ISSUE TITLE
Redeployment of daemonset cause errors with agent auth from wazuh-server side

### ISSUE THREAD

**Issue by okhotnikov-aa** [pyToshka/docker-wazuh-agent#12]
Hi
I met a problem with deploying wazuh-agent via daemonset 
Wazuh-server registers agents with their names and IPs.
Redeployments of daemonset pods cause pods IPs to change and that leads to the issues on the server side - with duplication of agents, with the same names but different IPs
Did you meet that issue?
Maybe you deal with it somehow from Calico's side, by stateful IP conf for those pods, or somehow else?

**Comment by pyToshka** [comment]
@okhotnikov-aa  Hi.
Could you please check latest build?

**Comment by pyToshka** [comment]
unfortunately i didnt get feedback, feel free for reopen
