### ISSUE TITLE
Error: secret "wazuh-api-cred" not found

### ISSUE THREAD

**Issue by Faarhad** [pyToshka/docker-wazuh-agent#15]
Hi @pyToshka 
Thank you for creating a daemonset for k8s.
after running the deamonset I faced a problem:
the pods are in **CreateContainerConfigError** state and when I check the reason:
Error: secret "wazuh-api-cred" not found.
what should I do now to solve this?
I really appreciate any help you can provide.

**Comment by pyToshka** [comment]
@Faarhad  hello, this error mean you have not secret named wazuh-api-cred, please configure daemon set for using credentials

**Comment by Faarhad** [comment]
@pyToshka Thank you for your quick response, I created a secret for that, but there's no svc for Wazuh deamonset.
please correct me if I'm wrong.
I installed Wazuh agent on my Linux OS, and I can see all machines logs in Wazuh manager, in order to monitor k8s I ran a deamonset just like the documentation said.
so I create a deamon set but now it's searching for a service. did I do that correctly? or for monitoring k8s components I should use Wazuh installation alternative: deployment on kubernetes?

**Comment by pyToshka** [comment]
@Faarhad  you should setup ENV based on your setup, please setup correct [envs](https://github.com/pyToshka/docker-wazuh-agent#environments) for daemonset.

**Comment by Faarhad** [comment]
Thank you @pyToshka, I fill out all envs requirements, 
This is my envs parameters:
I created a secret for deamonset, which it's username is admin (as wazuh default) and it's password is my wazuh dashboard pass. this is my rest of Yaml file:
`        env:
        - name: JOIN_MANAGER_MASTER_HOST
          value: "20.20.20.87" #this is IP address of wazuh manager dashboard
        - name: JOIN_MANAGER_WORKER_HOST
          value: "20.20.20.87"
        - name: JOIN_MANAGER_PROTOCOL
          value: "https"
        - name: FLASK_BIND
          value: "0.0.0.0"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: WAZUH_GROUPS
          value: default
        - name: JOIN_MANAGER_USER
          valueFrom:
           secretKeyRef:
             name: wazuh-secret
             key: username
        - name: JOIN_MANAGER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wazuh-secret
              key: password
        - name: JOIN_MANAGER_API_PORT
          value: "55000"
        - name: JOIN_MANAGER_PORT
          value: "1514"
        - name: HEALTH_CHECK_PROCESSES
          value: "ossec-execd,ossec-syscheckd,ossec-logcollector,wazuh-modulesd,ossec-authd"
`

now pods are created but with the state of CrashLoopBackOff
I think I'm missing a dumb point! 
Thank you for your patience and kind response.

**Comment by pyToshka** [comment]
@Faarhad  for CrashLoopBackOff need to check logs what the reason

**Comment by Faarhad** [comment]
is my env configuration correct?
        env:
        - name: JOIN_MANAGER_MASTER_HOST
          value: "20.20.20.87" #this is IP address of wazuh manager dashboard
        - name: JOIN_MANAGER_WORKER_HOST
          value: "20.20.20.87"
        - name: JOIN_MANAGER_PROTOCOL
          value: "https"
        - name: FLASK_BIND
          value: "0.0.0.0"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: WAZUH_GROUPS
          value: default
        - name: JOIN_MANAGER_USER
          valueFrom:
           secretKeyRef:
             name: wazuh-secret
             key: username
        - name: JOIN_MANAGER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wazuh-secret
              key: password
        - name: JOIN_MANAGER_API_PORT
          value: "55000"
        - name: JOIN_MANAGER_PORT
          value: "1514"
        - name: HEALTH_CHECK_PROCESSES
          value: "ossec-execd,ossec-syscheckd,ossec-logcollector,wazuh-modulesd,ossec-authd"

**Comment by Faarhad** [comment]
This is pods log:


2022-12-07 12:22:11.813 | INFO     | __main__:<module>:251 - Adding agent with name worker3
Traceback (most recent call last):
  File "/var/ossec/./register_agent.py", line 252, in <module>
    agent_id, agent_key = add_agent(node_name)
  File "/var/ossec/./register_agent.py", line 119, in add_agent
    status_code, response = req(
  File "/var/ossec/./register_agent.py", line 50, in req
    token = json.loads(response.content.decode())["data"]["token"]
KeyError: 'data'
root@master1:/home/sysadm# kubectl logs -f  wazuh-agent-dj78m  -n wazuh

**Comment by pyToshka** [comment]
> This is pods log:
> 
> 2022-12-07 12:22:11.813 | INFO | **main**::251 - Adding agent with name worker3 Traceback (most recent call last): File "/var/ossec/./register_agent.py", line 252, in agent_id, agent_key = add_agent(node_name) File "/var/ossec/./register_agent.py", line 119, in add_agent status_code, response = req( File "/var/ossec/./register_agent.py", line 50, in req token = json.loads(response.content.decode())["data"]["token"] KeyError: 'data' root@master1:/home/sysadm# kubectl logs -f wazuh-agent-dj78m -n wazuh

seems like agent couldn't connect to your Wazuh server
