### ISSUE TITLE
about the wazuh manager

### ISSUE THREAD

**Issue by yehaotong** [pyToshka/docker-wazuh-agent#4]
this agent can work with official wazuh-manager，sir？

**Comment by pyToshka** [comment]
@yehaotong sure this repository only about agent

**Comment by yehaotong** [comment]
@pyToshka sir，I am a wazuh beginner,I recently tried to build the agent side and manager side of wazuh locally in the form of dockerfile,I mean, I'm using the official docker wazuh ofDe provided by wazug and starting it. Can this wazuh agent be matched with the official wazuh manager? I don't know how to use dockerfile to build the agent side of wazuh.Thank you for your help

**Comment by yehaotong** [comment]
> @yehaotong确定这个存储库只关于代理
sir,I started the wazuh odfe officially provided by wazuh locally, and then I configured the join in the dockerfile of wazuh agent in this project_ MANAGER_ MASTER_ Host and join_ MANAGER_ WORKER_ Host, when I reported an error in the build container,

**Comment by yehaotong** [comment]
> @yehaotong确定这个存储库只关于代理

I started the wazuh odfe officially provided by wazuh locally, and then I configured the join in the dockerfile of wazuh agent in this project_ MANAGER_ MASTER_ Host and join_ MANAGER_ WORKER_ Host, when I reported an error in the build container：Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/requests/ (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f88283c9cc0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
#7 68.97   what can i do

**Comment by pyToshka** [comment]
@yehaotong  please follow instruction you should setup  [environments](https://github.com/pyToshka/docker-wazuh-agent#environments) for your Wazuh master server
`Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'` - mean name couldn't resolve from Your cluster
As well please check [run in k8s](Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')
